import type { Job, Candidate } from "./types";

export const INITIAL_JOBS: Job[] = [
  {
    id: "e5d53686-b8b6-4ec6-b8c2-71cd534641fb",
    title: "Email Designer BR — Figma",
    department: "Design",
    candidatesCount: 138,
    averageScore: 3.8,
    topScore: 4.8,
    status: "active",
    createdDate: "05/06/2026",
  },
  {
    id: "job-2",
    title: "React Frontend Developer",
    department: "Tecnologia",
    candidatesCount: 45,
    averageScore: 4.1,
    topScore: 4.9,
    status: "active",
    createdDate: "01/06/2026",
  },
  {
    id: "job-3",
    title: "Product Manager Pleno",
    department: "Produto",
    candidatesCount: 89,
    averageScore: 3.5,
    topScore: 4.7,
    status: "completed",
    createdDate: "15/05/2026",
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: "cand-1",
    name: "Tainá Reis",
    role: "Mid-level Designer",
    company: "Acerto",
    city: "São Paulo, SP",
    score: 4.8,
    avatarColor: "#0369A1",
    initials: "TR",
    confirmedTags: ["Figma", "Email Marketing"],
    partialTags: ["CRM"],
    otherTags: ["Inglês fluente"],
    shortlist: true,
    status: "shortlist",
    linkedinUrl: "#",
    email: "taina.reis@example.com",
    phone: "(11) 98765-4321",
    pretensaoSalarial: "R$ 6.000,00",
    disponibilidade: "Imediata",
    regime: "CLT ou PJ",
    observacoes: "Candidata muito forte em Figma, com ótimo portfólio. Pediu para avisar se houver teste prático.",
    evaluations: [
      { name: "Sólida experiência com design de Email Marketing", score: 4.8, justification: "Excelente portfólio de e-mail marketing na Acerto.", weight: 5 },
      { name: "Domínio avançado do Figma", score: 4.5, justification: "Menciona Figma como principal ferramenta.", weight: 4 },
      { name: "Inglês avançado ou fluente", score: 5.0, justification: "Possui inglês fluente.", weight: 3 },
    ]
  },
  {
    id: "cand-2",
    name: "Beatriz Garibalde",
    role: "Senior Designer",
    company: "LG Electronics",
    city: "São Paulo, SP",
    score: 4.1,
    avatarColor: "#D97706",
    initials: "BG",
    confirmedTags: ["Figma", "Newsletter"],
    partialTags: [],
    otherTags: ["Inglês intermediário"],
    shortlist: false,
    status: "triado",
    linkedinUrl: "#",
    email: "beatriz.gari@example.com",
    phone: "(11) 91234-5678",
    regime: "PJ",
    evaluations: [
      { name: "Sólida experiência com design de Email Marketing", score: 4.0, justification: "Boa experiência com Newsletter.", weight: 5 },
      { name: "Domínio avançado do Figma", score: 4.5, justification: "Usa Figma regularmente.", weight: 4 },
      { name: "Inglês avançado ou fluente", score: 3.0, justification: "Inglês intermediário apenas.", weight: 3 },
    ]
  },
  {
    id: "cand-3",
    name: "Marcos Carvalho",
    role: "Email Designer Freelancer",
    company: "Freelancer",
    city: "Curitiba, PR",
    score: 3.5,
    avatarColor: "#059669",
    initials: "MC",
    confirmedTags: ["Email Marketing"],
    partialTags: ["Figma", "CRM"],
    otherTags: [],
    shortlist: false,
    status: "triado",
    linkedinUrl: "#",
  },
  {
    id: "cand-4",
    name: "Juliana Souza",
    role: "Product Designer",
    company: "Nubank",
    city: "Rio de Janeiro, RJ",
    score: 4.9,
    avatarColor: "#7E22CE",
    initials: "JS",
    confirmedTags: ["Figma", "Design System", "UX Research"],
    partialTags: [],
    otherTags: ["Inglês fluente"],
    shortlist: true,
    status: "entrevista",
    linkedinUrl: "#",
  },
  {
    id: "cand-5",
    name: "Thiago Silva",
    role: "UI Developer",
    company: "Itaú",
    city: "Belo Horizonte, MG",
    score: 3.2,
    avatarColor: "#BE185D",
    initials: "TS",
    confirmedTags: ["Figma", "HTML/CSS"],
    partialTags: ["JavaScript"],
    otherTags: [],
    shortlist: false,
    status: "triado",
    linkedinUrl: "#",
  },
  {
    id: "cand-6",
    name: "Amanda Costa",
    role: "Marketing Designer",
    company: "VTEX",
    city: "Florianópolis, SC",
    score: 4.5,
    avatarColor: "#0369A1",
    initials: "AC",
    confirmedTags: ["Figma", "Copywriting"],
    partialTags: [],
    otherTags: ["Inglês fluente", "Edição de vídeo"],
    shortlist: true,
    status: "oferecido",
    linkedinUrl: "#",
  },
];

// Color palette for dynamically generated avatar backgrounds
export const AVATAR_COLORS = [
  "#0369A1", "#D97706", "#059669", "#7E22CE",
  "#BE185D", "#0891B2", "#4338CA", "#B45309",
];

export function getAvatarBg(hex: string): string {
  // Returns a lighter version for background
  const map: Record<string, string> = {
    "#0369A1": "#E0F2FE",
    "#D97706": "#FEF3C7",
    "#059669": "#D1FAE5",
    "#7E22CE": "#F3E8FF",
    "#BE185D": "#FCE7F3",
    "#0891B2": "#CFFAFE",
    "#4338CA": "#E0E7FF",
    "#B45309": "#FEF3C7",
  };
  return map[hex] || "#F1F5F9";
}
